---

- name: Install MongoDB
  hosts: db
  become: true
  tasks:

    - name: Apt-get update
      shell: apt-get update -y

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - libcurl3-gnutls
        - ca-certificates

    - name: Add apt key
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com

    - name: Add repository
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/{{ ansible_distribution|lower }} xenial/mongodb-org/4.2 multiverse"
        state: present
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Start MongoDB
      service:
        name: mongod
        state: started

    - name: Enable mongodb
      systemd:
        name: mongod
        enabled: yes
