---
- name: Install ruby & bunbler
  hosts: app
  become: true
  tasks:
    - name: Install
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ruby-full
        - ruby-bundler
        - build-essential
