---
- name: Install ruby & bunbler
  hosts: app
  become: true
  tasks:

    - name: Install ruby packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ruby-full
        - ruby-bundler
        - build-essential

    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
